# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-09 18:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
    ]
