# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-17 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('annex_accession_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_key', models.DateField(unique=True)),
                ('hay_accessions', models.IntegerField()),
                ('hay_refiles', models.IntegerField()),
                ('non_hay_accessions', models.IntegerField()),
                ('non_hay_refiles', models.IntegerField()),
                ('notes', models.TextField(null=True)),
            ],
        ),
    ]
